--0403

SELECT DEPTNO, ENAME, DECODE(DEPTNO, 10, 'ACCOUNTING', 20, 'RESEARCH', '30', 'SALES', 'ETC')
FROM EMP
ORDER BY DEPTNO;

SELECT COMM, DECODE(COMM, NULL, 0, COMM) FROM EMP;

SELECT GREATEST(3000,1500,2100), LEAST(3000, 1500, 2100, 5000) FROM DUAL;

--SELECT DEPTNO, ENAME, SAL, 
--DECODE(GREATEST(SAL,4800),SAL,'HIGH',DECODE(GREATEST(SAL,3000),SAL,'MID','LOW’))
--FROM EMP ORDER BY DEPTNO;

-- DECODE 사용해서 랜덤 번호 뽑기 --
--SELECT ROUND(DBMS_RANDOM.VALUE(0.5,21.5), 0) as Victim FROM DUAL;

SELECT DEPTNO, ENAME,
        CASE DEPTNO WHEN '10' THEN 'ACCOUNTING'
                    WHEN 20 THEN 'RESEARCH'
                    WHEN 30 THEN 'SALES'
                    ELSE         'ETC'
        END AS DEPARTMENT
FROM EMP
ORDER BY DEPTNO;

SELECT DEPTNO, ENAME, COMM,
        CASE    WHEN COMM >= 1000 THEN 'Great'
                WHEN COMM >= 500  THEN 'Good'
                WHEN COMM >= 0    THEN 'Bad'
        ELSE                            'Dreadful'  -- ELSE에서 NULL Catch
        END     COMM_GRADE
FROM EMP
ORDER BY DEPTNO;

--ROWNUM

SELECT ROWNUM, ENAME, DEPTNO, SAL FROM EMP;
SELECT ROWNUM,ENAME,DEPTNO,SAL FROM EMP ORDER BY DEPTNO,SAL;

SELECT ROWNUM, ENAME, DEPTNO, SAL FROM EMP WHERE DEPTNO IN (10,20) 
ORDER BY DEPTNO, SAL;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM =1;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM = 3;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM > 3;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM <= 3;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM < 3;
 
 -- AND OR NOT
 SELECT ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO = 10 AND SAL > 2000;
 SELECT ENAME, JOB, DEPTNO FROM EMP WHERE SAL > 2000;
 SELECT ENAME, JOB, DEPTNO FROM EMP WHERE SAL > 2000 OR SAL > 2000;
 
 -- 단일행 함수 문자함수
 
 SELECT ENAME, lower(ENAME), upper(ENAME), initcap(ENAME) FROM EMP;
 SELECT ENAME, substr(ENAME, 1, 3), substr(ENAME,4), substr(ENAME, -3, 2) 
 FROM EMP;
 --3
 SELECT ENAME, instr(ENAME, 'A'), instr(ENAME, 'A', 2), instr(ENAME, 'A', 1, 2) FROM EMP;
 --4
 SELECT ENAME, rpad(ENAME, 10, ' '), rpad(ENAME, 10), rpad(ENAME, 10, 
'*'), lpad(ENAME, 10, '*+') FROM EMP;
SELECT length(rpad('X',1000,'X')), rpad('X', 1000, 'X') FROM DUAL;
-- 5
SELECT ENAME, REPLACE(ENAME,'S','s') FROM EMP;
-- 6
SELECT ENAME, concat(ENAME, JOB), ENAME||JOB FROM EMP;
-- 7
SELECT ltrim(' 대한민국 '), rtrim(' 대한민국 '), trim(' ' from ' 대한민국 ' ), trim('*' from '**대한민국**')
FROM dual;
SELECT trim('장' from '장발장'), ltrim('장발장', '장'), rtrim('장발장','장') FROM dual;
-- 8
SELECT length('abcd'), substr('abcd',2,2), length('대한민국'), substr('대한민국',2,2)
FROM dual;
-- 9 
SELECT lengthb('abcd'), length('대한민국'), substr('대한민국', 2,2), substrb('대한민국', 2,2)
FROM dual;  -- substrb : byte로 처리해서 정삭적으로 출력이 안됨
-- lengthb / length 차이 
-- 10
SELECT length('abcd'), vsize('abcd'), length('대한민국'), vsize('대한민국')
FROM dual;
-- 11
SELECT ASCII('A'), ASCII('a')FROM dual;
-- 12
SELECT CHR(65), CHR(97) FROM DUAL;
SELECT 'Hello'||CHR(10)||'World' FROM DUAL;


-- DECODE
SELECT DEPTNO, SAL
FROM EMP;
-- 10번 부서 급여의 0.3% , 20번부서 급여의 20%, 30번 부서 급여의 10%, 나머지 모든 부서 1%
-- DECODE
SELECT DEPTNO, ENAME, JOB, SAL,
       ROUND(DECODE(DEPTNO, 10, SAL*0.003, 20, SAL*0.2, 30, SAL*0.1, SAL*0.01),2) AS BONUS
FROM EMP
--GROUP BY DEPTNO
ORDER BY DEPTNO, BONUS DESC;

-- CASE
SELECT DEPTNO, ENAME, JOB, SAL,
       CASE DEPTNO WHEN 10 THEN ROUND(SAL*0.003,2)
                   WHEN 20 THEN ROUND(SAL*0.2,2)
                   WHEN 30 THEN ROUND(SAL*0.1,2)
                   ELSE           ROUND(SAL*0.01,2)
        END AS BONUS
        FROM EMP
ORDER BY DEPTNO, BONUS DESC;

-- 7번
SELECT DEPTNO,JOB,
       DECODE(DEPTNO, 10 , DECODE(JOB,'CLERK','OK','NO'),'NO')
       FROM EMP
ORDER BY DEPTNO,JOB;

SELECT DEPTNO, JOB,
        DECODE(DEPTNO||JOB, 10||'CLERK', 'OK', 'NO')
        FROM EMP
ORDER BY DEPTNO, JOB;

-- 10 이면 CLERK OK / 이외 NO 
-- 10 이 아니면 CLECK NO

--SELECT DEPTNO, JOB,
--       DECODE(DEPTNO, 10,    
  
SELECT DEPTNO, ENAME, DECODE(DEPTNO,10,'ACCOUNTING',20,'RESEARCH','ETC')  FROM  EMP  ORDER BY DEPTNO;
     SELECT DEPTNO, ENAME, DECODE(DEPTNO,10,'ACCOUNTING',20,'RESEARCH')  FROM  EMP  ORDER BY DEPTNO;        
     
SELECT DEPTNO,JOB,ENAME FROM EMP WHERE  DEPTNO = 20;			
SELECT DEPTNO,JOB,ENAME FROM EMP WHERE  JOB = 'CLERK';			
SELECT DEPTNO,JOB,ENAME FROM EMP WHERE  DEPTNO = 20  OR JOB = 'CLERK' ;     
SELECT DISTINCT DEPTNO,JOB,ENAME FROM EMP WHERE  DEPTNO = 20  OR JOB = 'CLERK' ;     

SELECT * FROM EMP;

SELECT DEPTNO, ENAME, JOB, SAL,
        CASE WHEN ENAME LIKE '%S%' THEN 'HI'
        ELSE                       ' '
        END AS NAME2
FROM EMP;


SELECT DEPTNO, ENAME, JOB, SAL,
       CASE WHEN JOB LIKE '%SALES%' THEN 'SALES DEPARTMENT'
            WHEN JOB IN ('CLERK', 'MANAGER') THEN 'MANAGEMENT'
            ELSE 'OTHER DEPARTMENT'
            END AS DEPT_TYPE
FROM EMP
WHERE DEPTNO IN (10, 20);

SELECT DEPTNO, SAL, JOB, SAL,
ROUND(DECODE(DEPTNO,10, SAL*0.03, 20, SAL*0.2, 30, SAL*0.1, SAL*0.01),2) AS BONUS
FROM EMP
ORDER BY DEPTNO, BONUS DESC;

SELECT DEPTNO, SAL, JOB, SAL,
        CASE DEPTNO  WHEN 10 THEN ROUND(SAL*0.03, 2)
                     WHEN 20 THEN ROUND(SAL*0.2, 2) 
                     WHEN 30 THEN ROUND(SAL*0.1, 2)
                     ELSE          ROUND(SAL*0.01, 2)
                     END AS BONUS
FROM EMP
ORDER BY DEPTNO, BONUS DESC;

SELECT DEPTNO, ENAME, JOB,
        CASE WHEN JOB LIKE '%ANALYST%' THEN 'PRESS DEPARTMENT'
             WHEN JOB IN('CLERK', 'MANGER') THEN 'MANAGEMENT DEPARTMENT'
             ELSE 'OTHER DEPARTMENT'
             END AS BONUS
FROM EMP
ORDER BY DEPTNO, BONUS DESC;

SELECT DEPTNO, ENAME, JOB, SAL,
        DECODE(DEPTNO||JOB, 10||'CLERK', 'OK', 'NO')
        FROM EMP
ORDER BY DEPTNO, JOB;

SELECT COMM
FROM EMP
WHERE COMM = NULL;

SELECT COMM
FROM EMP
WHERE COMM IS NULL;

NULL = NULL 

SELECT DECODE(NULL, NULL, 1, 0) AS DECODE_NULL,
        
        CASE 
        WHEN NULL = NULL THEN 1
        ELSE 0
        END AS CASE_NULL_1
     
       ,CASE WHEN NULL IS NULL THEN 1
        ELSE 0
        END AS CASE_NULL_2
FROM EMP;

SELECT GREATEST(3000,1500,2100,5000),LEAST(3000,1500,2100,5000) FROM DUAL ;

SELECT DEPTNO, SAL, JOB, SAL,
        CASE DEPTNO  WHEN 10 THEN ROUND(SAL*0.03, 2)
                     WHEN 20 THEN ROUND(SAL*0.2, 2) 
                     WHEN 30 THEN ROUND(SAL*0.1, 2)
                     ELSE          ROUND(SAL*0.01, 2)
                     END AS BONUS
FROM EMP
ORDER BY DEPTNO, BONUS DESC;


-- SELECT DEPTNO,ENAME
--      CASE DEPTNO WHEN 10 THEN 'ACCOUNTING’ 
--                  WHEN 20 THEN 'RESEARCH'
--                  WHEN 30 THEN 'SALES'
--                   ELSE 'ETC'
--               END AS DEPARTMENT
--FROM EMP
--ORDER BY DEPTNO;

-- DATE TYPE
-- 1번
SELECT sysdate, sysdate + 7, sysdate -2, sysdate + 1/24 FROM dual;
-- 2번
SELECT DEPTNO, ENAME, TRUNC(SYSDATE - HIREDATE) AS WORK_DAY
FROM EMP
ORDER BY DEPTNO, WORK_DAY DESC;

-- ALTER USER scott identified by tiger;

-- 3번
SELECT ENAME, SYSDATE, HIREDATE,
        to_char(SYSDATE,'YYYY-MM-DD:HH24:MI:SS'),to_char(HIREDATE,'YYYY-MM-DD:HH24:MI:SS')
        FROM EMP;
-- 4번
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD:HH24:MI:SS';
SELECT ENAME, SYSDATE, HIREDATE 
FROM EMP;
SELECT SYSDATE FROM DUAL;

desc v$mystat
select sid from v$mystat;