SELECT TO_CHAR(SYSDATE,'DDD'),TO_CHAR(SYSDATE,'DD'),TO_CHAR(SYSDATE,'D') FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- 3번
SELECT 
DECODE (TO_CHAR(LAST_DAY(SYSDATE),'D'),1,LAST_DAY(SYSDATE)-2, 
       7, LAST_DAY(SYSDATE)-1, 
       LAST_DAY(SYSDATE)) AS "LAST DAY"
FROM DUAL;

-- 4번
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-RR';
SELECT * FROM EMP WHERE HIREDATE LIKE '82%';
SELECT * FROM EMP WHERE HIREDATE LIKE '%82';

SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'RR') LIKE '82%';
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'RR') = '82';

-- 6번
SELECT DEPTNO, MAX(SAL), MIN(SAL)
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- 7번
SELECT TO_CHAR(HIREDATE,'YYYY')AS NEW_HIREDATE, MAX(SAL), MIN(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY')
ORDER BY NEW_HIREDATE;

-- 8번
SELECT 
    MAX(DECODE(DEPTNO, 10, COUNT(*))) AS "10번부서",
    MAX(DECODE(DEPTNO, 20, COUNT(*))) AS "20번부서",
    MAX(DECODE(DEPTNO, 30, COUNT(*))) AS "30번 부서"
FROM EMP
GROUP BY DEPTNO;

SELECT 
    COUNT(DECODE(DEPTNO, 10, DEPTNO)) AS "10번부서",
    COUNT(DECODE(DEPTNO, 20, DEPTNO)) AS "20번부서",
    COUNT(DECODE(DEPTNO, 30, DEPTNO)) AS "30번 부서"
FROM EMP;

--9번
SELECT * FROM CUSTOMER
SAMPLE(10)
WHERE ROWNUM <= 10;

SELECT * FROM CUSTOMER
SAMPLE(5)
SEED(1234)
WHERE ROWNUM <= 10;


SELECT SYSDATE, 
        TO_CHAR(SYSDATE,'YEAR'), TO_CHAR(SYSDATE,'Year'), TO_CHAR(SYSDATE,'YYYY'), TO_CHAR(SYSDATE,'YY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'MONTH'), TO_CHAR(SYSDATE,'MON'), TO_CHAR(SYSDATE,'Mon'), TO_CHAR(SYSDATE,'mon'), TO_CHAR(SYSDATE,'MM'), TO_CHAR(SYSDATE,'mm')
FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE,'DAY'), TO_CHAR(SYSDATE,'Day'), TO_CHAR(SYSDATE,'DY'), TO_CHAR(SYSDATE,'dy'), TO_CHAR(SYSDATE,'DD'), TO_CHAR(SYSDATE,'dd')
FROM DUAL;

SELECT 123456, 
TO_CHAR(123456,'999999'), LENGTH(TO_CHAR(123456,'999999')),LENGTH(TO_CHAR(123456,'fm999999')), REPLACE(TO_CHAR(123456,'999999'),' ','BLANK')
FROM DUAL;

-- REPLACE 함수를 통해 공백문자를 치환함
SELECT 123456, TO_CHAR(123456,'999999'), LENGTH(TO_CHAR(-123456,'999999')),
     LENGTH(TO_CHAR(-123456,'fm999999')) 
     FROM DUAL;

SELECT -123456, TO_CHAR(-123456,'999999'), LENGTH(TO_CHAR(-123456,'999999')),
     LENGTH(TO_CHAR(-123456,'fm999999')) 
     FROM DUAL;

SELECT TO_CHAR(12345123.45,'9,999,999,999.99'),TO_CHAR(12345123.45,'99,999,999.99') 
FROM DUAL;

SELECT TO_CHAR(SAL,'$999,999'), REPLACE(TO_CHAR(SAL,'$999,999'),' ','?'),
TO_CHAR(SAL,'L999,999'), TO_CHAR(SAL,'999,999L'), TO_CHAR(SAL,'fm999,999L')
FROM EMP;

DESC EMP;

SELECT SAL,COMM FROM EMP;
SELECT SUM(NVL(COMM,0)) AS SUM_COMM1,
SUM(COMM) AS SUM_COMM2,
NVL(SUM(COMM),0) AS SUM_COMM3
FROM EMP;

SELECT DEPTNO,COUNT(SAL) FROM SCOTT.EMP GROUP BY DEPTNO;
SELECT DEPTNO,COUNT(*) FROM SCOTT.EMP GROUP BY DEPTNO;

SELECT DEPTNO,AVG(SAL) ,SUM(SAL) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO,AVG(SAL) ,SUM(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT DEPTNO, ROUND(AVG(SAL),1), SUM(SAL) FROM EMP 
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT COMM,COUNT(*) FROM EMP GROUP BY COMM;

SELECT DEPTNO,COUNT(*),SUM(SAL),ROUND(AVG(SAL),1) FROM EMP
GROUP BY DEPTNO;