--1
SELECT DNAME, ENAME, JOB, SAL 
FROM EMP, DEPT WHERE DEPTNO = DEPTNO;
--2
SELECT DNAME, ENAME, JOB, SAL 
FROM SCOTT.EMP, SCOTT.DEPT 
WHERE EMP.DEPTNO = DEPT.DEPTNO;
--3
SELECT DNAME, ENAME, JOB, SAL FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB IN ('MANAGER', 'CLERK')
ORDER BY DNAME;
--4
SELECT D.DNAME, E.ENAME, E.JOB, E.SAL 
FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO;

--5
SELECT D.DNAME,E.ENAME,E.JOB,E.SAL FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

--6
SELECT D.DNAME, E.ENAME, E.JOB, E.JOB, E.SAL FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IN (10,20) AND D.DNAME = 'RESEARCH';

-- OUTER JOIN(+) 
--1
SELECT D.DNAME, E.ENAME, E.JOB, E.JOB, E.SAL 
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DETPNO
ORDER BY D.DNAME;
--2
SELECT D.DNAME,E.ENAME,E.JOB,E.SAL FROM EMP E,DEPT D WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DNAME;
--3
SELECT D.DNAME,E.ENAME,E.JOB,E.SAL FROM EMP E,DEPT D WHERE E.DEPTNO = D.DEPTNO(+)
ORDER BY D.DNAME;
--4 // EQUI-JOIN과 동일한 결과 출력, 불필요함
SELECT D.DNAME,E.ENAME,E.JOB,E.SAL 
FROM EMP E,DEPT D WHERE E.DEPTNO = D.DEPTNO(+)
ORDER BY D.DNAME;
--5
SELECT D.DNAME,NVL(E.ENAME,'비상근 부서'),E.JOB,E.SAL FROM EMP E,DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DNAME;
--6
SELECT D.DNAME,E.ENAME,E.JOB,E.SAL FROM EMP E,DEPT D WHERE E.DEPTNO(+) = D.DEPTNO(+)
ORDER BY D.DNAME;

-- ANSI 
SELECT E.DEPTNO, D.DNAME, E.ENAME 
FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO;

SELECT E.DEPTNO, D.DNAME, E.ENAME 
FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO;

SELECT D.DEPTNO, D.DNAME, E.ENAME 
FROM SCOTT.EMP E FULL OUTER JOIN SCOTT.DEPT D ON E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO;

-- SELF-JOIN(순환관계)
SELECT E.ENAME||' ''S MANAGER IS '||M.ENAME
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO
ORDER BY M.ENAME;

SELECT * FROM EMP;

-- 과제1
SELECT E.ENAME||' ''S MANAGER IS '||M.ENAME 
FROM EMP E, EMP M
WHERE E.MGR(+) = M.EMPNO 
ORDER BY M.ENAME;

-- 카티션곱
--1 
SELECT ENAME,JOB,DNAME FROM EMP, DEPT;
SELECT ENAME,JOB,DNAME FROM EMP CROSS JOIN DEPT;

--2
SELECT ENAME,JOB,DNAME FROM EMP , DEPT
WHERE EMP.SAL > 2000 AND DEPT.DEPTNO IN (10,20);

SELECT * FROM EMP; --16행
SELECT * FROM DEPT;  -- 20행

--3
SELECT ENAME,JOB,DNAME FROM EMP , DEPT
WHERE EMP.SAL > 2000 OR DEPT.DEPTNO IN (10,20);

--4
SELECT E.ENAME, E.JOB, E.SAL, S.GRADE FROM EMP E, SALGRADE S
WHERE E.SAL < S.LOSAL AND E.DEPTNO IN (10, 30)
ORDER BY E.ENAME;

SELECT * FROM EMP;
SELECT * FROM SALGRADE;

-- DEPTNO가 10 또는 30이고, SALGRADE 테이블의 LOSAL보다 작은 SAL 값을 갖는 EMP 레코드만 출력
SELECT E.ENAME, E.JOB,E.SAL,S.GRADE FROM EMP E, SALGRADE S
WHERE E.SAL < S.LOSAL AND E.DEPTNO IN (10,30)
ORDER BY E.ENAME;
-- 조인 조건을 명시하지 않았기 때문에 좋은 방법이 아님 
-- 수정 
SELECT E.ENAME, E.JOB, E.SAL, S.GRADE
FROM EMP E INNER JOIN SALGRADE S 
ON E.SAL < S.LOSAL 
WHERE E.DEPTNO IN (10,30)
ORDER BY E.ENAME;
