--1
CREATE VIEW VW_SIMPLE
AS SELECT EMP.EMPNO,EMP.ENAME,DEPT.DNAME,SALGRADE.GRADE AS GD
    FROM EMP, DEPT, SALGRADE
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND 
        EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL;
--2 
DESC VW_SIMPLE

SELECT * FROM TAB;
--3
SELECT * FROM VW_SIMPLE;

-- 독립성
--1 
CREATE TABLE BASE_TBL(EMPNO_NEW, ENAME_NEW)
AS SELECT EMPNO, ENAME
    FROM EMP
    WHERE JOB IN ('CLERK','SALESMAN');

desc base_tbl
select * from tab;

CREATE VIEW VW_IND AS SELECT * FROM BASE_TBL;
SELECT * FROM VW_IND;

ALTER TABLE BASE_TBL ADD(NEW_COL DATE);

SELECT * FROM VW_IND;
SELECT EMPNO_NEW,ENAME_NEW FROM VW_IND;

-- 다변성
--1 
CREATE TABLE DBA_TBLS
AS SELECT OWNER, TABLE_NAME FROM DBA_TABLES;

SELECT * FROM DBA_TBLS;
SELECT OWNER, COUNT(*)
FROM DBA_TBLS
GROUP BY OWNER;

--2
CREATE OR REPLACE VIEW VW_DIFF
AS SELECT * FROM DBA_TBLS WHERE OWNER = USER;

SELECT * FROM VW_DIFF;
SELECT count(*) FROM VW_DIFF; 

--3 
GRANT SELECT ON VW_DIFF TO PUBLIC;

--4
SELECT * FROM VW_DIFF;
SELECT count(*) FROM VW_DIFF; 

--VIEW MERGE
--1 VIEW 정의
CREATE VIEW VW_DEPTEMP 
AS SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO;

--[VIEW 질의] 
SELECT * FROM VW_DEPTEMP WHERE DNAME = 'SALES';

--[VIEW 처리] 
SELECT E.EMPNO,E.ENAME,E.SAL,D.DEPTNO,D.DNAME
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO AND D.DNAME = 'SALES';

-- [Stored Query]
SELECT VIEW_NAME,TEXT FROM USER_VIEWS;

-- SYNONYM
--1 
SELECT * FROM SALGRADE;

CREATE SYNONYM SALG FOR SALGRADE;